name: Strapi CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        env:
          ENV_VAR1: value1
          ENV_VAR2: value2
          ENV_VAR3: value3

      - name: Change directory to 'myproject'
        run: cd my-project

      - name: Build Strapi
        run: npm run build

      - name: Run Strapi tests
        run: npm test
